### ISSUE TITLE
Increment return value is large

### ISSUE THREAD

**Issue by alex-taxiera** [alex-taxiera/simple-knex#10]
We can only increment a single column at a time, yet we always return the entire table as the 'updated' value. There are also options for where and where not for the increment method, so we should select an updated value to return similarly. like `this.select({ table, columns: column, where, whereNot })` this will provide the minimum amount of data that was updated.

**Comment by mets11rap** [comment]
I think it's better code-wise for a couple of reasons:
1. It's easier to utilize an updated table in the code without re-selecting
2. It doesn't have any speed benefits considering it iterates over the whole table anyway (And it's not that much of a RAM benefit considering it wouldn't be that much. If it were such a big table anyway, you'd probably make sure your PC can handle it)
